Block c
Ozymandy/tc pull request #3
Opened 2016-10-27 19:46 UTC by Ozymandy

2016-10-28 12:42 UTC, UladzimirKapylou requested changes
All comments should be fixed not only in place they where left, but in ALL similar places as well.

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/controllers/CourseController.java
> +    private UserCourseServiceInterface userCourseService;
It is a bad idea to use word Interface in interface name.

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/controllers/CourseController.java
> +    public void initBinder(WebDataBinder binder) {
Do you really need this method? I believe, that default resolver should work by default, without any additional configuration.

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/controllers/CourseController.java
> +        mav.addObject("h1", "Courses");
h1 - bad name for your data

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/controllers/CourseController.java
> +        mav.addObject("h1", "Course details");
this key is used in several places. It should be refactored to constant

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/controllers/CourseController.java
>              ModelAndView mav = new ModelAndView("classpath:views/update");
it is better to use constants instead of string literals at all here

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/controllers/CourseController.java
> +        Subscribers subs = new Subscribers();
This is a bad place to create and fill domain objects

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/controllers/CourseController.java
> +        if (courseService.isSubscribed(auth.getName(), id)) {
userService.isSubscribed(User, Course) would be more clear interface than
courseService.isSubscribed(String, int)
And you do have userCourseService it is probably better to use it to define relations between user and course.

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/controllers/CourseController.java
> +        Authentication auth = SecurityContextHolder
you can even dare to extract this to smth like get(Current)User() method and use it everywhere

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/controllers/CourseController.java
> +        Attendee attendee = new Attendee();
Again, bad place

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/controllers/CourseController.java
> +        boolean state = courseService.isEvaluated(auth.getName(), id);
variable name doesn't reflect its content, and BTW is never used :)

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/controllers/CourseController.java
> +                                 @ModelAttribute("evaluation") Evaluation evaluation) {
Why do you get Evaluation object in parameters on GET?

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/controllers/CourseController.java
> +        userCourseService.create(subs);
userCourseService.subscribe(User, Course) probably would be much better

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/controllers/CourseController.java
> +        userCourseService.create(attendee);
userCourseService.attend(User, Course);

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/dao/evaluation/EvaluationDao.java
> +    public List<Evaluation> getByUserId(int id) {
Where is this method used and why?

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/dao/evaluation/EvaluationDao.java
> +    public List<Evaluation> getAll() {
Where is this method used?

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/utils/converters/CourseDTOConverter.java
> +        //is it bad?
Probably.
Most likely :)

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/models/usercourse/Attendee.java
> +public class Attendee extends UserCourse {
Attendee is a person. How he can be inherited from UserCourse? Looks like class name (Attendee) is not slightly correct.

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/services/course/CourseService.java
>              throw new CourseNotFoundException("Course not found");
It probably would be helpful to log this here.

2016-10-28 12:42 UTC, UladzimirKapylou commented on src/main/java/org/tc/services/course/CourseService.java
> +        if (course != null && (user.getId() == course.getUser().getId())) {
what if user is null here?

2016-10-28 13:50 UTC, Ozymandy commented on src/main/java/org/tc/controllers/CourseController.java
> +        mav.addObject("h1", "Course details");
No, it's different from page to page

2016-10-28 14:15 UTC, UladzimirKapylou commented on src/main/java/org/tc/controllers/CourseController.java
> +        mav.addObject("h1", "Course details");
Ok, if key is different, how it can be used in template single standard way? I still believe that key is the same everywhere.

2016-10-28 16:27 UTC, Ozymandy commented on src/main/java/org/tc/controllers/CourseController.java
> +        mav.addObject("h1", "Course details");
Because I have th:fragment header, where I set this value. On course page it's "Courses", on /details/, as here, it's "Course details" and so on

2016-10-29 09:34 UTC, Ozymandy commented on src/main/java/org/tc/controllers/CourseController.java
> +                                 @ModelAttribute("evaluation") Evaluation evaluation) {
I define this in th:object in thymeleaf, so I need set it to parameters

2016-10-29 09:35 UTC, Ozymandy commented on src/main/java/org/tc/controllers/CourseController.java
> +        boolean state = courseService.isEvaluated(auth.getName(), id);
Yes, It was for debug, and I forgot to remove this

2016-10-29 09:36 UTC, Ozymandy commented on src/main/java/org/tc/services/course/CourseService.java
>              throw new CourseNotFoundException("Course not found");
This have no sense for debug. It's just for `ExceptionHandler`

2016-10-30 19:51 UTC, merged